name: lz_flutter

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  fluttertoast: ^3.1.3
  chopper: ^2.5.3
  floor: ^0.12.0
  synchronized: '>=1.5.1 <4.0.0'
  shared_preferences: '>=0.4.1 <3.0.0'
  path_provider: '>=1.2.0 <3.0.0'
  json_annotation: ^3.0.0
